#!/bin/sh

commit="$(git log --oneline | head -n 1 | awk '{print $1}')"
date="$(date -Iseconds)"
user="yoshuawuyts"

run_build () {
  docker_projectname="$user/$1"
  docker build "$1" \
    -t "$docker_projectname:latest" \
    -t "$docker_projectname:$commit" \
    --label "date=$date" \
    --label "commit=$commit"
}

run_publish () {
  run_build "$@"
  docker_projectname="$user/$1"
  docker push "$docker_projectname:latest"
  docker push "$docker_projectname:$commit"
}

usage () {
  printf 'Usage: script/build [options]'
}

# set CLI flags
args="$(getopt pho "$*")"
[ $? -ne 0 ] && { usage; exit 2; }
eval set -- "$args"

# parse CLI flags
while true; do
  case "$1" in
    -h ) usage ;;
    -o ) shift; run_optimize "$@"; break ;;
    -p ) shift; run_publish "$@"; break ;;
    * ) shift; run_build "$@"; break ;;
  esac
done
