################################################################################
#
# Base Debian installation
#
################################################################################

FROM debian:wheezy
MAINTAINER Yoshua Wuyts <i@yoshuawuyts.com>

RUN apt-get update && apt-get install -y \
    curl \
    git
